### ISSUE TITLE
Missing provided anatomical segmentation models

### ISSUE THREAD

**Issue by Schuture** [alexanderjaus/AtlasDataset#4]
Hi! Our group appreciates your excellent work very much and is willing to follow your work to further explore whole-body segmentation. But we didn't find the provided anatomical segmentation models (v1 and v2) in this repo. Is there any way that we can download it?

**Comment by alexanderjaus** [comment]
Hi @Schuture
you can download the models by clicking on the GDrive Models and Datasets shield. This should take you to a Google Drive Repo. As an alternative, you may also use this link.
https://drive.google.com/drive/folders/1WIlvpeKAWNS99sFprkGKtNZkHm-3agLf

**Comment by Schuture** [comment]
Thank you for your response, but there are only three datasets available in the Google Drive repo for me, is that the correct repo?

**Comment by alexanderjaus** [comment]
There should be 3 files in the Google Drive repo: 
- Atlas_dataset: The dataset
- Task901_Atlas_Dataset.zip : The nnUnet model we used to create the atlas dataset (data has to be post processed) 
- Task902_ Anatomy_Prediction.zip: The nnUnet model we used to conduct OOD testings
